"""Add interest model

Revision ID: 1412d5ba8ff7
Revises: fc072821fc77
Create Date: 2025-07-17 17:38:20.789914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1412d5ba8ff7'
down_revision: Union[str, None] = 'fc072821fc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_id', table_name='stock')
    op.drop_index('ix_stock_ticker', table_name='stock')
    op.drop_table('stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stock_pkey')
    )
    op.create_index('ix_stock_ticker', 'stock', ['ticker'], unique=True)
    op.create_index('ix_stock_id', 'stock', ['id'], unique=False)
    # ### end Alembic commands ###
