"""add name to avatar

Revision ID: 46f9e3be7f57
Revises: d3d0681cb4b1
Create Date: 2025-08-05 18:57:53.003624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f9e3be7f57'
down_revision: Union[str, None] = 'd3d0681cb4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatar', 'name')
    # ### end Alembic commands ###
