"""add name column to avatar

Revision ID: be9ff9efae83
Revises: 1b6b8c333c24
Create Date: 2025-08-03 16:56:57.823535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9ff9efae83'
down_revision: Union[str, None] = '1b6b8c333c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatar', sa.Column('name', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatar', 'name')
    # ### end Alembic commands ###
