"""add loss column to avartar

Revision ID: f29461450e01
Revises: b8e4b60a0e12
Create Date: 2025-08-03 13:54:51.449979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29461450e01'
down_revision: Union[str, None] = 'b8e4b60a0e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avartar', sa.Column('loss', sa.Integer(), nullable=False))
    op.drop_column('avartar', 'loss_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avartar', sa.Column('loss_ratio', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('avartar', 'loss')
    # ### end Alembic commands ###
